plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - ARCHETYPE.md
  - index.md
  - gdb_cheatsheet.md
  - XXE.md
  - Adding ourselves to AdminSDHolder.md
theme: jekyll-theme-hacker
